apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cpeir
rules:
- apiGroups: [""]
  resources: ["nodes","persistentvolumeclaims","pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["config.openshift.io"]
  resources: ["clusterversions"]
  verbs: ["get", "list"]
