apiVersion: v1
kind: ConfigMap
metadata:
  name: cpeir-config
data:
  cp4application-4.0.1.yaml: |
    system:
      cpu: 1000m
      memory: 4Gi
  cp4multicloud.yaml: |
    system:
      cpu: 3000m
      memory: 10Gi
