apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpeir
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cpeir
  template:
    metadata:
      labels:
        name: cpeir
    spec:
      serviceAccountName: cpeir
      containers:
        - name: cpeir
          # Replace this with the built image name
          image: ibmcloudacademy/cpeir:02
          command:
          - cpeir
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cpeir"
