apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpeir
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cpeir
  template:
    metadata:
      labels:
        name: cpeir
    spec:
      serviceAccountName: cpeir
      containers:
        - name: cpeir
          # Replace this with the built image name
          image: ibmgaragetsa/cpeir:v0.001
          command:
          - cpeir
          volumeMounts:
          - name: cpcfg
            mountPath: /cfgdata
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cpeir"
        - name: runtime
          image: ibmgaragetsa/cpeir-runtime:v0.001
          imagePullPolicy: Always
          command:
            - bash
            - start.sh
          volumeMounts:
          - name: cpcfg
            mountPath: /cfgdata
      volumes:
      - name: cpbin
        emptyDir: {}
      - name: cpcfg
        emptyDir: {}
