kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cpeir
subjects:
- kind: ServiceAccount
  name: cpeir
roleRef:
  kind: Role
  name: cpeir
  apiGroup: rbac.authorization.k8s.io
