kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cpeir
subjects:
- kind: ServiceAccount
  name: cpeir
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cpeir
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cpeir-registry
subjects:
- kind: ServiceAccount
  name: cpeir
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
  namespace: openshift-image-registry
