apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cpeirs.cloud.ibm.com
spec:
  group: cloud.ibm.com
  names:
    kind: CPeir
    listKind: CPeirList
    plural: cpeirs
    singular: cpeir
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CPeir is the Schema for the cpeirs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CPeirSpec defines the desired state of CPeir
          properties:
            cpfeatures:
              items:
                type: string
              type: array
            cpsizetype:
              type: string
            cptype:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            cpversion:
              type: string
          required:
          - cpfeatures
          - cptype
          - cpversion
          type: object
        status:
          description: CPeirStatus defines the observed state of CPeir
          properties:
            clusterStatus:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              enum:
              - Initial
              - NotInstallable
              - ReadyToInstall
              - Installed
              - ValidationFailed
              - UpgradeAvailable
              type: string
            clustercpu:
              type: string
            clustermemory:
              type: string
            clusterstorage:
              type: string
            cpreqcpu:
              type: string
            cpreqmemory:
              type: string
            cpreqstorage:
              type: string
            installedFeatures:
              items:
                type: string
              type: array
            statusMessages:
              type: string
          required:
          - clusterStatus
          - statusMessages
          type: object
      required:
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
