apiVersion: cloud.ibm.com/v1alpha1
kind: CPeir
metadata:
  name: cp4multicloud
spec:
  cptype: "cp4multicloud"
  cpversion: "2.0.0"
  cpsizetype: "default"
  storageClass: "ocs-storagecluster-ceph-rbd"
  cpfeatures: []
  action: "Check"
