// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPeir) DeepCopyInto(out *CPeir) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPeir.
func (in *CPeir) DeepCopy() *CPeir {
	if in == nil {
		return nil
	}
	out := new(CPeir)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CPeir) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPeirList) DeepCopyInto(out *CPeirList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CPeir, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPeirList.
func (in *CPeirList) DeepCopy() *CPeirList {
	if in == nil {
		return nil
	}
	out := new(CPeirList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CPeirList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPeirSpec) DeepCopyInto(out *CPeirSpec) {
	*out = *in
	if in.CPFeatures != nil {
		in, out := &in.CPFeatures, &out.CPFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPeirSpec.
func (in *CPeirSpec) DeepCopy() *CPeirSpec {
	if in == nil {
		return nil
	}
	out := new(CPeirSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPeirStatus) DeepCopyInto(out *CPeirStatus) {
	*out = *in
	if in.InstalledFeatures != nil {
		in, out := &in.InstalledFeatures, &out.InstalledFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPeirStatus.
func (in *CPeirStatus) DeepCopy() *CPeirStatus {
	if in == nil {
		return nil
	}
	out := new(CPeirStatus)
	in.DeepCopyInto(out)
	return out
}
